apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: i0clb5tbp-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-feadf363cc.a3a4.p3.openshiftapps.com/rhtap/rhtap-qe:aa886d82b671e17f6af099b89090f4914cf1cd70@sha256:09eb1856209dce29a2178a61d6c223687cb7c84412cd9b1c30f69d70a1d26287
          name: container-image
